services:
  ksi-mock:
    image: mockserver/mockserver:5.15.0
    restart: unless-stopped
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
    volumes:
      - ./initializerJson.json:/config/initializerJson.json:ro
